name: jupytergis
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy
  - xarray
  - zarr
  - s3fs
  - h5netcdf
  - cftime
  - nbqa
  - ruff
  - black
  - isort
  - nbconvert
  - pytest
  - pytest-cov
  - jupyter
  - mystmd
  - jupytergis
  - qgis
  - ipykernel
  - jupyter_client
  - nbformat
  - nodejs=18  # For mystmd CLI
